id: eb769e97-f6dd-471a-90ee-29d4666e0718
alias: 00 🏠 Turn everything off when nobody is home"
mode: single
max_exceeded: silent
trigger:
  - platform: state
    entity_id: sensor.house_mode
    to: "Afwezig"
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
condition:
  - alias: "Niemand thuis?"
    condition: state
    entity_id: sensor.house_mode
    state: "Afwezig"
action:
  #  - alias: "Turn on recording for cameras"
  #    service: switch.turn_on
  #    target:
  #      entity_id:
  #        - switch.floris_recordings
  #        - switch.pepijn_recordings
  - alias: "Enable sending of snapshots on motion"
    service: input_boolean.turn_on
    target:
      entity_id: input_boolean.motion_snapshots
  - alias: "TV on"
    choose:
      - conditions:
          - condition: not
            conditions:
              - alias: "Shield off"
                condition: state
                entity_id: media_player.shield
                state: "off"
        sequence:
          - alias: "Enable guest mode to avoid that they will be in the dark"
            service: input_boolean.turn_on
            target:
              entity_id: input_boolean.gast
    default:
      - alias: "All lights off"
        service: light.turn_off
        target:
          entity_id: light.groep_huis
      - alias: "Media players off"
        service: media_player.turn_off
        target:
          entity_id: all
      - alias: "Turn off extractor hood if needed?"
        choose:
          - conditions:
              - alias: "Afzuigkap of lichtje actief?"
                condition: numeric_state
                entity_id: sensor.afzuigkap_power
                above: 1
            sequence:
              - alias: "Turn off plug"
                service: switch.turn_off
                target:
                  entity_id: switch.afzuigkap
      - alias: "Turn off plug for TV if not active"
        choose:
          - conditions:
              - alias: "TV Meubel verbruikt weinig power"
                condition: numeric_state
                entity_id: sensor.tv_meubel_power
                below: 40
            sequence:
              - alias: "TV Meubel uit"
                service: switch.turn_off
                target:
                  entity_id: switch.tv_meubel
      - alias: "Turn off plug for dryer if not active"
        choose:
          - conditions:
              - alias: "Droger verbruikt weinig power"
                condition: numeric_state
                entity_id: sensor.droger_power
                below: 40
            sequence:
              - alias: "Droger switch uit"
                service: switch.turn_off
                target:
                  entity_id: switch.droger
      - alias: "Turn of desk Marleen if not active"
        choose:
          - conditions:
              - alias: "Computer Marleen uit"
                condition: state
                entity_id: binary_sensor.imac_marleen
                state: "off"
              - condition: not
                conditions:
                  - alias: "Printer actief"
                    condition: state
                    entity_id: sensor.dcp_l2530dw_status
                    state: "printing"
              - alias: "Weinig verbruik"
                condition: numeric_state
                entity_id: sensor.bureau_marleen_power
                below: 20
            sequence:
              - alias: "Bureau Marleen uit"
                service: switch.turn_off
                target:
                  entity_id: switch.bureau_marleen
      - alias: "Turn off desk Martijn if not active"
        choose:
          - conditions:
              - alias: "Computer Martijn uit"
                condition: state
                entity_id: binary_sensor.computer_zolder
                state: "off"
            sequence:
              - alias: "Bureau Martijn uit"
                service: switch.turn_off
                target:
                  entity_id: switch.bureau_martijn
