id: bfebcb80-6ccb-4c72-ba04-8c5be2befba8
alias: "Zolder - Plug droger uitzetten"
trigger:
  - platform: numeric_state
    entity_id: sensor.droger_power
    above: 20
    for: "00:05:00"
    id: "active"
  - platform: numeric_state
    entity_id: sensor.droger_power
    below: 20
    for: "00:15:00"
    id: "inactive"
action:
  - alias: "Active of Inactive"
    choose:
    - conditions:
        - condition: trigger
          id: "active"
      sequence:
        - alias: "Input boolean aanzetten"
          service: input_boolean.turn_on
          target:
            entity_id: input_boolean.droger_active
    - conditions:
        - condition: trigger
          id: "inactive"
        - alias: "Actief geweest"
          condition: state
          entity_id: input_boolean.droger_active
          state: "on"
      sequence:
        - alias: "Switch uitzetten"
          service: switch.turn_off
          target:
            entity_id: switch.droger
        - alias: "Input boolean aanzetten"
          service: input_boolean.turn_off
          target:
            entity_id: input_boolean.droger_active

