id: fab3e0d1-1d3a-46ce-b1c1-5c56e788bf02
alias: "F2 📦 Status messages for printer"
trigger:
  - platform: numeric_state
    entity_id: sensor.dcp_l2530dw_black_toner_remaining
    below: 26
    id: toner
  - platform: numeric_state
    entity_id: sensor.dcp_l2530dw_drum_remaining_life
    below: 26
    id: drum
  - platform: numeric_state
    entity_id: sensor.dcp_l2530dw_black_toner_remaining
    below: 11
    id: toner
  - platform: numeric_state
    entity_id: sensor.dcp_l2530dw_drum_remaining_life
    below: 11
    id: drum
condition:
  - alias: "Previous state is not unavailable or unkown"
    condition: template
    value_template: "{{ trigger.from_state.state not in ['unavailable', 'unknown'] }}"
action:
  - variables:
      external_url: !secret ha_url
  - alias: "Which notification"
    choose:
      - conditions:
          - alias: "Toner"
            condition: trigger
            id: toner
        sequence:
          - alias: "Notificatie naar telefoon Martijn"
            service: notify.join_pixel5
            data:
              title: "Printer toner status"
              message: "De toner is nog maar voor {{ states('sensor.dcp_l2530dw_black_toner_remaining') }}% vol"
              data:
                icon: "{{ external_url }}/local/pictures/printer.png"
                smallicon: "{{ external_url }}/local/pictures/printer.png"
      - conditions:
          - alias: "Drum"
            condition: trigger
            id: drum
        sequence:
          - alias: "Notificatie naar telefoon Martijn"
            service: notify.join_pixel5
            data:
              title: "Printer drum status"
              message: "De levensduur van de drum is nog maar {{ states('sensor.dcp_l2530dw_drum_remaining_life') }}%"
              data:
                icon: "{{ external_url }}/local/pictures/printer.png"
                smallicon: "{{ external_url }}/local/pictures/printer.png"
