id: 991bfa0a-ba49-462b-b78a-2aed72317903
alias: "F2 📦 Notifications washing machine"
mode: single
max_exceeded: silent
trigger:
  - entity_id: sensor.wasmachine_remain_time
    platform: state
    from: 0:01
    to: 0:00
action:
  - variables:
      external_url: !secret ha_url
  - alias: "Notification to phone Marleen"
    service: notify.mobile_app_marleen_app
    data:
      title: "💦 Wasmachine is klaar"
      message: "Haal snel de was er uit voordat het allemaal kreukt."
  - alias: "Notification to phone Martijn"
    service: notify.join_pixel5
    data:
      title: "Wasmachine is klaar"
      message: "Haal snel de was er uit voordat het allemaal kreukt."
      data:
        icon: "{{ external_url }}/local/pictures/laundry.png"
        smallicon: "{{ external_url }}/local/pictures/laundry.png"
