id: c4a98059-5bc4-4335-9cc3-07ebe673dabd
alias: "F1F 👶 Motion detection FlorisCam on and off"
mode: single
max_exceeded: silent
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: time
    at:
      - "07:00"
      - "18:30"
action:
  - alias: "Time?"
    choose:
      - conditions:
          - condition: time
            before: " 06:59:59"
        sequence:
          - alias: "Motion detection Floriscam on"
            service: switch.turn_on
            target:
              entity_id: switch.floriscam_state
      - conditions:
          - condition: time
            before: "18:29:59"
        sequence:
          - alias: "Motion detection Floriscam off"
            service: switch.turn_off
            target:
              entity_id: switch.floriscam_state
    default:
      - alias: "Motion detection Floriscam on"
        service: switch.turn_on
        target:
          entity_id: switch.floriscam_state
