id: c4a98059-5bc4-4335-9cc3-07ebe673dabd
alias: "F1F 👶 Motion detection FlorisCam on and off"
mode: single
max_exceeded: silent
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: time
    at:
      - "07:00"
      - "19:00"
condition:
  - alias: "Someone home?"
    condition: state
    entity_id: group.m_en_m
    state: "home"
action:
  - alias: "Time?"
    choose:
      - conditions:
          - condition: time
            after: "07:00:00"
            before: "19:00:00"
        sequence:
          - alias: "Motion detection Floriscam off"
            service: switch.turn_off
            target:
              entity_id: switch.floris_recordings
      - conditions:
          - condition: time
            after: "19:00:00"
            before: "07:00:00"
        sequence:
          - alias: "Motion detection Floriscam off"
            service: switch.turn_off
            target:
              entity_id: switch.floris_recordings
