id: c4a98059-5bc4-4335-9cc3-07ebe673dabd
alias: "F1F ⏺ Enable or disable recording of cameras Floris"
mode: single
max_exceeded: silent
trigger:
  - platform: state
    entity_id:
      - binary_sensor.floris_person_motion
    from: "unavailable"
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.floris_light_inside
    to: ~
    for: "00:02:00"
  - platform: state
    entity_id: binary_sensor.cleaning_time
  - platform: time
    at:
      - "19:00"
      - "07:30"
  - platform: state
    entity_id: sensor.house_mode
    from:
variables:
  switches:
    - switch.floris_recordings
    - switch.floris_snapshots
    - switch.floris_detect
action:
  - alias: "Which action"
    choose:
      - conditions:
          - alias: "Cleaning time"
            condition: state
            entity_id: binary_sensor.cleaning_time
            state: "on"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: "{{ switches }}"
      - conditions:
          - condition: or
            conditions:
              - alias: "Bedtime"
                condition: time
                after: " 19:00:00"
              - condition: and
                conditions:
                  - alias: "Dark inside bedroom Floris"
                    condition: state
                    entity_id: binary_sensor.floris_light_inside
                    state: "off"
                  - alias: "Sun still up"
                    condition: state
                    entity_id: sun.sun
                    state: "above_horizon"
              - condition: not
                conditions:
                  - alias: "Nobody home"
                    condition: state
                    entity_id: sensor.house_mode
                    state: "Thuis"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: "{{ switches }}"
    default:
      - service: switch.turn_on
        target:
          entity_id: "{{ switches | reject('search', 'recordings') | list }}"
      - service: switch.turn_off
        target:
          entity_id: "{{ switches | select('search', 'recordings') | list }}"
