id: 6743d0cc-19ad-4f18-8ae6-1cd69364a611
alias: "F1F 👶 Turn input boolean on and off on release switch"
mode: parallel
max_exceeded: silent
trigger:
  - platform: event
    event_type: esphome.button_pressed
    event_data:
      device: Floris
      click_type: release
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.floris_release
  - delay: 0.5
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.floris_release
