id: shelly_knop_floris_release
alias: "Eerste verdieping | Floris - Knop loslaten"
mode: parallel
max_exceeded: silent
trigger:
  - platform: event
    event_type: esphome.button_pressed
    event_data:
      device: Floris
      click_type: release
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.floris_release
  - delay: 0.5
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.floris_release
