binary_sensor:
  unique_id: 1676e0c4-f873-406f-8223-c0c0565f0039
  name: "Temperature Livingroom"
  device_class: door
  state: >-
    {{ 
      states('sensor.woonkamer_temp') | float(0.0) > states('sensor.br_temperature') | float(0.0) 
      and states('sensor.woonkamer_temp') | float(0.0) > 21
    }}
  delay_on: "00:05:00"
  delay_off: "00:05:00"
