binary_sensor:
  unique_id: b998425b-81e2-41da-bb0c-4e9564035e68
  name: "Temperature Floris"
  device_class: window
  state: >-
    {{ 
      states('sensor.floris_temp') | float(0.0) > states('sensor.br_temperature') | float(0.0) 
      and states('sensor.floris_temp') | float(0.0) > 21
    }}
  delay_on: "00:05:00"
  delay_off: "00:05:00"
