- id: "1632656512140"
  alias: F2 📦 Xiaomi Cube
  description: Acties voor cube
  use_blueprint:
    path: bergstrom/mi-magic-cube-deconz-45-actions.yaml
    input:
      remote: f6774ae0411495f22b9ffa91f9f11c0b
      cube_shake:
        - service: switch.turn_on
          target:
            entity_id: switch.bureau_martijn
      rotate_clockwise:
        - service: media_player.volume_set
          target:
            entity_id: media_player.zolder_mini_martijn
          data:
            volume_level:
              "{{ [1, state_attr('media_player.zolder_mini_martijn', 'volume_level')
              | float + 0.05 ] | min | round(2) }}"
      rotate_counter_clockwise:
        - service: media_player.volume_set
          target:
            entity_id: media_player.zolder_mini_martijn
          data:
            volume_level:
              "{{ [0, state_attr('media_player.zolder_mini_martijn', 'volume_level')
              | float - 0.05 ] | max | round(2) }}"
