id: 9d731a57-843d-452e-96f1-a35469df2d86
alias: "00 🔧 Update HACS log"
mode: queued
max: 50
trigger:
  - platform: time
    at: "00:00:00"
action:
  - service: shell_command.remove_hacs_file
  - delay: 0.5
  - alias: "All integrations"
    service: notify.hacs_installed
    data:
      message: |
        {%- set h = state_attr('sensor.hacs_installed', 'installed') %}
        Update:
        ## ALL ##
        Total number: {{ states('sensor.hacs_installed') | int }}
        {%- for i in h %}
          * Name: {{ i.name }}
            URL: {{ i.url }}
            Version: {{ i.version }}
        {%- endfor %}
