id: 6d4f5447-5b96-4753-a943-eeb79695d466
alias: "00 🔧 Notifications Overkiz not working"
variables:
  messages:
    - Overkiz ligt weer plat
    - Ohoh, het is weer zo ver Overkiz doet het niet
    - De screens zijn niet beschikbaar
  minutes_alert_repeat: 30
  check_entities:
    - light.veranda
    - cover.floris_tahoma
    - cover.pepijn_tahoma
    - cover.slaapkamer_links
    - cover.slaapkamer_midden
    - cover.slaapkamer_rechts
    - cover.veranda
trigger:
  - platform: state
    entity_id:
      - light.veranda
      - cover.floris_tahoma
      - cover.pepijn_tahoma
      - cover.slaapkamer_links
      - cover.slaapkamer_midden
      - cover.slaapkamer_rechts
      - cover.veranda
    to: "unavailable"
action:
  - alias: "Send notification"
    repeat:
      while:
        - alias: All unavailable?
          condition: template
          value_template: >
            {{
              exand(check_entities) 
                | selectattr('state', 'eq', 'unavailable') 
                | list 
                | count
              == check_entities | count
            }}
      sequence:
        - service: notify.mobile_app_pixel_5
          data:
            title: "Overkiz integratie"
            message: "{{ messages | random }}"
            data:
              channel: Overkiz
              ttl: 0
              priority: high
              notification_icon: mdi:blinds
              actions:
                - action: "overkiz_reboot"
                  title: "Herstart HA"
        - delay:
            minutes: "{{ minutes_alert_repeat }}"
  - alias: "Still all unavailable?"
    condition: template
    value_template: >
      {{
        exand(check_entities) 
          | selectattr('state', 'eq', 'unavailable') 
          | list 
          | count
        == check_entities | count
      }}
  - alias: "Wait for a response"
    wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "overkiz_reboot"
  - alias: "Perform the action"
    service: homeassistant.restart
