id: 8b5eb1fe-6ced-4435-82a0-7b4b6c62e832
alias: "Algemeen | Cast - Volume wijzigen en terugzetten bij casten"
mode: parallel
max_exceeded: silent
trigger:
  - platform: state
    id: playing
    entity_id:
      - media_player.woonkamer_mini
      - media_player.keuken_hub
      - media_player.zolder_stereo
      - media_player.floris_mini
      - media_player.pepijn_mini
      - media_player.slaapkamer_hub
      - media_player.zolder_mini_martijn
      - media_player.zolder_mini_marleen
    to: "playing"
  - platform: state
    id: stopped_playing
    entity_id:
      - media_player.woonkamer_mini
      - media_player.keuken_hub
      - media_player.zolder_stereo
      - media_player.floris_mini
      - media_player.pepijn_mini
      - media_player.slaapkamer_hub
      - media_player.zolder_mini_martijn
      - media_player.zolder_mini_marleen
    to:
      - "off"
      - "idle"
    for: "00:00:06"
condition:
  - alias: "Wijziging in state?"
    condition: template
    value_template: "{{ (trigger.from_state.state != trigger.to_state.state) and trigger.from_state.state not in ['unavailable'] }}"
  - alias: "Google TTS script niet actief"
    condition: state
    entity_id:
      - script.google_home_say
    state: "off"
variables:
  player: "{{ trigger.entity_id }}"
  device: "{{ trigger.entity_id | replace('media_player.', '') }}"
  app: "{{ trigger.to_state.attributes.app_name | default('geen', true) }}"
  type: "{{ trigger.to_state.attributes.media_content_type | default('geen', true) }}"
  state_to: "{{ trigger.to_state.state }}"
  volume: "{{ state_attr(trigger.to_state.entity_id, 'volume_level') | round(2, default=0.25) }}"
  binary_sensor: "{{ trigger.to_state.entity_id | replace('media_player', 'binary_sensor') }}"
action:
  - alias: "Aan of uit?"
    choose:
      - conditions:
          - alias: "Aan het afspelen?"
            condition: trigger
            id: playing
          - alias: "Nog niet aan het spelen?"
            condition: template
            value_template: "{{ is_state(binary_sensor, 'off') }}"
        sequence:
          - alias: "Nieuws of muziek?"
            choose:
              - conditions:
                  - alias: "Nieuws?"
                    condition: template
                    value_template: "{{ app == 'Google News' }}"
                sequence:
                  - alias: "Juiste volume voor nieuws instellen"
                    service: media_player.volume_set
                    target:
                      entity_id: "{{ player }}"
                    data:
                      volume_level: 0.3
              - conditions:
                  - alias: "Muziek?"
                    condition: template
                    value_template: "{{ type == 'music' }}"
                sequence:
                  - alias: "Juiste volume voor muziek instellen"
                    service: media_player.volume_set
                    target:
                      entity_id: "{{ player }}"
                    data:
                      volume_level: 0.25
      - conditions:
          - alias: "Aan het afspelen?"
            condition: trigger
            id: stopped_playing
        sequence:
          - alias: "Volume weer naar het oude"
            service: media_player.volume_set
            target:
              entity_id: "{{ player }}"
            data:
              volume_level: "{{ state_attr(binary_sensor, 'volume') | float(0.25) }}"
