id: 57fd8a56-c026-4011-afa6-0f73f1a44cf2
alias: "Algemeen | Cast - Synchroniseer volume benedengroep"
mode: parallel
max_exceeded: silent
trigger:
  - platform: state
    entity_id:
      - media_player.keuken_hub
      - media_player.woonkamer_mini
    attribute: volume_level
condition:
  - alias: "Groep actief?"
    condition: state
    entity_id:
      - media_player.beneden_groep
    state: "playing"
  - alias: "Volume verschillend?"
    condition: template
    value_template: "{{ state_attr('media_player.keuken_hub', 'volume_level') != state_attr('media_player.woonkamer_mini', 'volume_level') }}"
action:
  - alias: "Volume syncen"
    service: media_player.volume_set
    target:
      entity_id:
        - media_player.keuken_hub
        - media_player.woonkamer_mini
    data:
      volume_level: "{{ trigger.to_state.attributes.volume_level }}"
