id: 28e079ed-9263-47c6-80bc-257fea3c4651
alias: "00 🔊 Cast audio and send TTS to mom"
mode: single
max_exceeded: silent
variables:
  player: media_player.woonkamer_mini
  notification_to: notify.mobile_app_marleen_app
  volume_tts: 40
  message_list: "{{ state_attr('input_select.mama', 'options') }}"
trigger:
  platform: event
  event_type: tag_scanned
  event_data:
    tag_id: 23-F4-7F-16
action:
  - variables:
      playlist: "{{ range(0, message_list | count) | list }}"
      exclude_list: "{{ states('input_text.played_mama').split('|') | map('int') | list }}"
      to_play: "{{ playlist | reject('in', exclude_list) | list | random }}"
      message: "{{ message_list[to_play] }}"
  - alias: "Remove oldest message from input_text, and add the latest one"
    service: input_text.set_value
    target:
      entity_id: input_text.played_mama
    data:
      value: "{{ ((states('input_text.played_mama').split('|') | map('int') | list)[1:] + [to_play]) | join('|') }}"
  - alias: "Send notification to phone"
    service: "{{ notification_to }}"
    data:
      title: "💖 Mama is.."
      message: "{{ message }}"
  - alias: "Send TTS"
    service: script.turn_on
    target:
      entity_id: script.google_home_say
    data:
      variables:
        tts_message: "{{ message }}"
        tts_target: "{{ player }}"
        tts_volume: " {{ volume_tts }}"
