id: afcf34ca-7a3e-4f49-a332-9313d2a2eca5
alias: "F0H 🔔 Actions based on doorbell"
trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_button
    to: "on"
mode: single
max_exceeded: silent
variables:
  hue_lights:
    - light.slaapkamer
    - light.eettafel
    - light.zolder_bol
  lights_doorbell:
    - light.slaapkamer
    - light.floris
    - light.pepijn
    - light.staande_lamp
action:
  - alias: "Notification for phones"
    service: notify.all_phones
    data:
      title: "🔔 Ding dong!"
      message: Er staat iemand aan de deur!
      data:
        channel: Deurbel
        importance: high
        priority: high
        ttl: 0
        notification_icon: mdi:bell
  - alias: "Nvidia Shield active?"
    choose:
      - conditions:
          - alias: "Shield active"
            condition: not
            conditions:
              - condition: state
                entity_id: media_player.nvidia_shield
                state: "off"
        sequence:
          - alias: "Pause Shield"
            service: media_player.media_pause
            target:
              entity_id: media_player.nvidia_shield
  - alias: "Google Home attic active or someone there"
    choose:
      - conditions:
          - condition: or
            conditions:
              - alias: "Google zolder Martijn actief?"
                condition: state
                entity_id: media_player.zolder_mini_martijn
                state: "playing"
              - alias: "Google zolder Marleen actief?"
                condition: state
                entity_id: media_player.zolder_mini_marleen
                state: "playing"
              - alias: "Marleen on attic"
                condition: state
                entity_id: sensor.location_phone_marleen
                state: "Zolder"
              - alias: "Martijn on attic"
                condition: state
                entity_id: sensor.location_phone_martijn
                state: "Zolder"
        sequence:
          - alias: "TTS Ding Dong for Google Home"
            service: script.turn_on
            target:
              entity_id: script.google_home_say
            data:
              variables:
                tts_message: "Ding Dong! Er staat iemand aan de deur!"
                tts_target: media_player.zolder_mini_martijn
                tts_volume: 35
  - alias: "Chime off and someone home?"
    choose:
      # Blink lights when chime is off and someone is home
      - conditions:
          - alias: "Chime off?"
            condition: state
            entity_id: switch.doorbell_chime_active
            state: "off"
          - alias: "Someone home?"
            condition: state
            entity_id: group.m_en_m
            state: "home"
        sequence:
          - alias: "Determine which lights are one and should blink"
            variables:
              lights: >
                {{ expand(lights_doorbell) | selectattr('state','eq','on') | map(attribute='entity_id') | list }}
          - alias: "Create scene with current state"
            service: scene.create
            data:
              scene_id: before
              snapshot_entities: "{{ [ 'light.zolder_bol', 'light.eettafel', 'light.voordeur' ] + lights }}"
          - alias: "Blink lights (hue_lights)"
            service: light.turn_on
            target:
              entity_id: "{{ ['light.eettafel', 'light.zolder_bol'] + lights | select('in', hue_lights) | list }}"
            data:
              flash: long
          - alias: "ESPHome lights to blink?"
            choose:
              - conditions:
                  - alias: "ESPHome lights on?"
                    condition: template
                    value_template: "{{ lights | reject('in', hue_lights) | list | length > 0 }}"
                sequence:
                  - alias: "Blink lights (ESPHome)"
                    service: light.turn_on
                    target:
                      entity_id: "{{ lights | reject('in', hue_lights) | list }}"
                    data:
                      effect: "Fast Pulse"
          - alias: "Blink front door light using loop"
            repeat:
              count: 10
              sequence:
                - alias: "Knipper voordeur"
                  service: light.toggle
                  data:
                    entity_id: light.voordeur
                - alias: "Pauze tussen knipper"
                  delay: 0.5
          - alias: "Restore state"
            service: scene.turn_on
            target:
              entity_id: scene.before
      # Blink front door light when nobody is home
      - conditions:
          - alias: "Chime not active"
            condition: state
            entity_id: switch.doorbell_chime_active
            state: "off"
          - alias: "Nobobdy home?"
            condition: state
            entity_id: group.m_en_m
            state: "not_home"
        sequence:
          - alias: "Create scene with current state"
            service: scene.create
            data:
              scene_id: before
              snapshot_entities: light.voordeur
          - alias: "Loopje met knipper"
            repeat:
              count: 10
              sequence:
                - alias: "Blink"
                  service: light.toggle
                  data:
                    entity_id: light.voordeur
                - alias: "Pauze tussen knipper"
                  delay: 0.5
          - alias: "Restore scene"
            service: scene.turn_on
            target:
              entity_id: scene.before
  - alias: "Delay to avoid too much blinking"
    delay: 10
