sensor:
  - name: Prijs Energie Laag
    state: >
      {{
        [
          state_attr('sensor.prijs_energie_laag', 'levering'),
          state_attr('sensor.prijs_energie_laag', 'belasting'),
          state_attr('sensor.prijs_energie_laag', 'opslag')
        ] | map('float', 0) | sum
      }}
    icon: mdi:cash
    unique_id: bfdd9cdc-f552-4277-8734-1177edbba321
    unit_of_measurement: "€/kWh"
    attributes:
      levering: 0.08978
      belasting: 0.11408
      opslag: 0.03630
