sensor:
  - name: Prijs Energie Hoog
    state: >
      {{
        [
          state_attr('sensor.prijs_energie_hoog', 'levering'),
          state_attr('sensor.prijs_energie_hoog', 'belasting'),
          state_attr('sensor.prijs_energie_hoog', 'opslag')
        ] | map('float', 0) | sum
      }}
    icon: mdi:cash
    unique_id: aba81bc1-8320-4c7a-b9c2-87279951552e
    unit_of_measurement: "€/kWh"
    attributes:
      levering: 0.09595
      belasting: 0.11408
      opslag: 0.03630
