sensor:
  unique_id: 0cf831e0-bd64-44cb-867e-31835d77f062
  name: HACS installed
  icon: mdi:robot
  state: >
    {{ expand(integration_entities('hacs'))
        | selectattr('attributes.installed_version', 'defined')
        | map(attribute='entity_id')
        | select('match', '^update.')
        | list
        | count
    }}
  attributes:
    installed: >
      {%- set ns = namespace(hacs=[]) %}
      {%- for i in expand(integration_entities('hacs')) | selectattr('domain' , 'eq', 'update') %}
        {% if i.attributes.installed_version is defined %}
          {%- set n = i.attributes.friendly_name | replace(' update', '') %}
          {%- set r = i.attributes.release_url %}
          {%- set v = i.attributes.installed_version %}
          {%- set ns.hacs = ns.hacs + [dict(name=n, version=v, url=r)] %}
        {% endif%}
      {%- endfor %}
      {{ ns.hacs }}
