sensor:
  unique_id: sensor_huis_modus
  name: Huis Modus
  state: >-
    {% if is_state('group.m_en_m', 'not_home') 
        and is_state('input_boolean.gast', 'off') 
        and is_state('input_boolean.vakantie', 'on') %}
      Vakantie
    {% elif is_state('group.m_en_m', 'not_home') 
        and is_state('input_boolean.gast', 'on') %}
      Gast
    {% elif is_state('group.m_en_m', 'not_home') %}
      Afwezig
    {% 
      elif 
        is_state('group.m_en_m', 'home') 
        and 
          (
            as_timestamp(now()) | timestamp_custom('%H:%M') >= '22:30' 
            or now().hour < 6
          ) 
        and 
          ( 
            is_state('sensor.pixel_5_type_oplader', 'wireless') 
            or not is_state('person.martijn', 'home')
          )
        and 
          ( 
            is_state('sensor.de_buurvrouw_battery_state', 'Charging') 
            or not is_state('person.marleen', 'home')
          )
        and is_state('light.groep_beneden', 'off')
      %}
      Slapen
    {% else %}
      Thuis
    {% endif %}
  icon: >-
    {% if is_state('sensor.huis_modus', 'Gast') %}
      mdi:account
    {% elif is_state('sensor.huis_modus', 'Afwezig') %}
      mdi:home-outline
    {% elif is_state('sensor.huis_modus', 'Vakantie') %}
      mdi:bag-suitcase
    {% elif is_state('sensor.huis_modus', 'Slapen') %}
      mdi:bed
    {% else %}
      mdi:home
    {% endif %}
