sensor:
  unique_id: sensor_keukenspotjes_modus
  name: Keukenspotjes
  state: >-
    {% if is_state('switch.keukenspotjes', 'on') 
        and state_attr('switch.keukenspotjes', 'current_consumption') | float(0) > 0.5 %}
      Licht aan
    {% elif is_state('switch.keukenspotjes', 'on') %}
      Licht uit
    {% else %}
      Plug uit
    {% endif %}
  icon: >-
    {% if is_state('sensor.keukenspotjes_modus', 'Licht aan') %}
      mdi:lightbulb
    {% elif is_state('sensor.keukenspotjes_modus', 'Licht uit') %}
      mdi:lightbulb-off-outline
    {% elif is_state('sensor.keukenspotjes_modus', 'Plug uit') %}
      mdi:power-plug-off-outline
    {% endif %}
