sensor:
  unique_id: 6da8e3ab-38a9-4897-89e5-192802ff6894
  name: Measured Power
  unit_of_measurement: "W"
  state_class: measurement
  device_class: power
  state: >-
    {% 
      set reject_entities = 
            [
              'sensor.tv_lamp_power', 
              'sensor.samsung_soundbar_power_meter', 
              'sensor.measured_power', 
              'sensor.unknown_power', 
              'sensor.zolder_bol_power'
            ] 
    %}
    {{ 
      states.sensor
        | selectattr('entity_id', 'search', '_power') 
        | rejectattr('entity_id', 'search', 'estimated_power')   
        | rejectattr('entity_id', 'in', reject_entities)
        | selectattr('attributes.state_class', 'eq', 'measurement')
        | rejectattr('state', 'in', ['unavailable', 'unknown'])
        | map(attribute='state')
        | map('int')
        | sum
    }}
  attributes:
    entities_included: >
      {% 
        set reject_entities = 
            [
              'sensor.tv_lamp_power', 
              'sensor.samsung_soundbar_power_meter', 
              'sensor.measured_power', 
              'sensor.unknown_power', 
              'sensor.zolder_bol_power'
            ] 
      %}
      {{ 
        expand(states.sensor) 
          | selectattr('entity_id', 'search', '_power') 
          | rejectattr('entity_id', 'search', 'estimated_power')   
          | rejectattr('entity_id', 'in', reject_entities)
          | selectattr('attributes.state_class', 'eq', 'measurement')
          | rejectattr('state', 'in', ['unavailable', 'unknown'])
          | map(attribute='name') 
          | list 
      }}
  icon: mdi:flash
