sensor:
  unique_id: sensor_telefoon_martijn
  name: Telefoon Martijn
  state: >-
    {% if is_state('person.martijn', 'not_home') %}
      Niet thuis
    {% elif not is_state('person.martijn', 'home') %}
      {{ states('person.martijn') }}
    {% elif is_state('sensor.pixel_5_wifi_bssid', '2c:3a:fd:bf:2c:fb') %}
      Zolder
    {% elif is_state('sensor.pixel_5_wifi_bssid', '2c:3a:fd:df:6d:a5') %}
      Eerste verdieping
    {% 
      elif is_state('sensor.pixel_5_wifi_bssid', '3c:a6:2f:f9:ee:c3') 
      or is_state('sensor.pixel_5_wifi_bssid', '2c:91:ab:e6:1b:7c') 
    %}
      Beneden
    {% else %}
      Thuis
    {% endif %}
  picture: '/api/image/serve/7dce8363a8fd22c90115bbada5ff395a/512x512'