sensor:
  - unique_id: 9d6b50c5-6059-4d91-ae4e-43dcd095987c
    name: Rest en GFT
    state: >-
      {% set sensor = 'sensor.afvalwijzer_restgft' %}
      {% set type = sensor.split('_')[1] %}
      {% set today = states('sensor.afvalwijzer_today').split(', ') %}
      {% set tomorrow = states('sensor.afvalwijzer_tomorrow').split(', ') %}
      {% set days = ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag' ] %}
      {% if type in today %}
        Vandaag
      {% elif type in tomorrow %}
        Morgen
      {% else %}
        {{ days[as_local(as_datetime(state_attr(sensor, 'year_month_day_date'))).weekday()] ~ ' ' ~ states(sensor) }}
      {% endif %}
    icon: mdi:trash-can
    attributes:
      collection_date: >
        {% set sensor = 'sensor.afvalwijzer_restgft' %}
        {% set type = sensor.split('_')[1] %}
        {% set today = states('sensor.afvalwijzer_today').split(', ') %}
        {% if type in today %}
          {{ now().date() }}
        {% else  %}
          {{ as_local(as_datetime(state_attr(sensor, 'year_month_day_date'))).date() }}
        {% endif %}

  - unique_id: 821b207c-5c06-4da4-9e8c-a5790e6e4c8c
    name: Papier en PMD
    state: >-
      {% set sensor = 'sensor.afvalwijzer_dhm' %}
      {% set type = sensor.split('_')[1] %}
      {% set today = states('sensor.afvalwijzer_today').split(', ') %}
      {% set tomorrow = states('sensor.afvalwijzer_tomorrow').split(', ') %}
      {% set days = ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag' ] %}
      {% if type in today %}
        Vandaag
      {% elif type in tomorrow %}
        Morgen
      {% else %}
        {{ days[as_local(as_datetime(state_attr(sensor, 'year_month_day_date'))).weekday()] ~ ' ' ~ states(sensor) }}
      {% endif %}
    icon: mdi:trash-can-outline
    attributes:
      collection_date: >
        {% set sensor = 'sensor.afvalwijzer_dhm' %}
        {% set type = sensor.split('_')[1] %}
        {% set today = states('sensor.afvalwijzer_today').split(', ') %}
        {% if type in today %}
          {{ now().date() }}
        {% else  %}
          {% set date = state_attr(sensor, 'year_month_day_date') %}
          {% set date = as_local(as_datetime(date)).date() if date else 'unavailable' %}
          {{ date }}
        {% endif %}

  - unique_id: ff7c02aa-aea3-42a7-91f5-f1a8f88a8986
    name: Kerstboom
    state: >-
      {% set sensor = 'sensor.afvalwijzer_kerstbomen' %}
      {% set type = sensor.split('_')[1] %}
      {% set today = states('sensor.afvalwijzer_today').split(', ') %}
      {% set tomorrow = states('sensor.afvalwijzer_tomorrow').split(', ') %}
      {% set days = ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag' ] %}
      {% if type in today %}
        Vandaag
      {% elif type in tomorrow %}
        Morgen
      {% else %}
          {% set date = state_attr(sensor, 'year_month_day_date') %}
          {% set date = as_local(as_datetime(date)).date() if date else 'unavailable' %}
          {{ date }}
      {% endif %}
    icon: mdi:pine-tree
    attributes:
      collection_date: >
        {% set sensor = 'sensor.afvalwijzer_kerstbomen' %}
        {% set type = sensor.split('_')[1] %}
        {% set today = states('sensor.afvalwijzer_today').split(', ') %}
        {% if type in today %}
          {{ now().date() }}
        {% else  %}
          {% set date = state_attr(sensor, 'year_month_day_date') %}
          {% set date = as_local(as_datetime(date)).date() if date else 'unavailable' %}
          {{ date }}
        {% endif %}
