sensor:
  unique_id: defa0d9f-ce65-4af1-a63e-a1bbe14c4092
  name: Unknown Power
  unit_of_measurement: "W"
  state_class: measurement
  device_class: power
  state: >-
    {{ [0, states('sensor.power_consumption') | float(0) | multiply(1000) - [ states('sensor.estimated_power'), states('sensor.measured_power')] | map('float', 0) | sum] | max }}
  icon: mdi:flash
