sensor:
  - unique_id: e1638c75-58ff-422a-8242-51311716feee
    name: "Meter water"
    unit_of_measurement: m3
    state_class: total_increasing
    state: >
      {{ 
        (
          states('input_number.correction_water_meter') | float(0) 
          + states('sensor.yearly_water') | float(0)
        ) | round(3)
      }}
  - unique_id: 398d2263-18b8-48d0-b463-1fbf873b50f7
    name: "Watermeter usage in L"
    state: "{{ (states('sensor.water_meter_total_consumption') | float(0) * 1000) | int }}"
    state_class: measurement
    icon: mdi:water
