sensor:
  - unique_id: e1638c75-58ff-422a-8242-51311716feee
    name: "Meter water"
    unit_of_measurement: m3
    state_class: total_increasing
    state: >
      {{ 
        (
          states('input_number.correction_water_meter') | float(0) 
          + states('sensor.yearly_water') | float(0)
        ) | round(3)
      }}
