id: 3fd99480-be86-44d6-a3dd-678c832d6366
alias: "F0 🚽 Toilet light on and off"
mode: restart
max_exceeded: silent
trigger:
  - platform: state
    entity_id: binary_sensor.motion_wc
    to: "on"
    from: "off"
action:
  - alias: "Turn light on"
    service: light.turn_on
    target:
      entity_id: light.wc
  - alias: "Wait until motion stopped..."
    wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.motion_wc
        from: "on"
        to: "off"
  - alias: "Delay after motion stopped"
    delay:
      minutes: 5
  - alias: "Turn light off"
    service: light.turn_off
    target:
      entity_id: light.wc
