id: wc_lamp_automatisch_aan
alias: "Beneden | WC - Lamp automatisch aan"
mode: restart
max_exceeded: silent
trigger:
  - platform: state
    entity_id: binary_sensor.motion_wc
    to: "on"
    from: "off"
action:
  - alias: "Lamp in WC aanzetten"
    service: light.turn_on
    target:
      entity_id: light.wc
  - alias: "Wacht tot er geen motion meer is..."
    wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.motion_wc
        from: "on"
        to: "off"
  - alias: "Extra delay nadat er geen beweging meer is..."
    delay: 300
  - alias: "Lamp weer uit"
    service: light.turn_off
    target:
      entity_id: light.wc