binary_sensor:
  unique_id: b5744de8-ad22-4f26-b21d-aad62cf996a0
  name: "Beneden Groep"
  device_class: running
  state: >-
    {{ is_state('media_player.beneden_groep', 'playing') }}
  delay_off: "00:00:05"
  delay_on: "00:00:05"
  attributes:
    volume: 0.25
