binary_sensor:
  unique_id: e27a3d8e-510b-4135-bb9f-f3b2d3318834
  name: "Keuken Hub"
  device_class: running
  state: >-
    {{ is_state('media_player.keuken_hub', 'playing') }}
  delay_off: "00:00:05"
  delay_on: "00:00:05"
  attributes:
    volume: 0.25
