binary_sensor:
  unique_id: 1ba86851-4e5a-42e5-889d-2dac131fa778
  name: "Zolder Groep"
  device_class: running
  state: >-
    {{ is_state('media_player.zolder_groep', 'playing') }}
  delay_on: "00:00:05"
  delay_off: "00:00:05"
  attributes:
    volume: 0.25
