binary_sensor:
  unique_id: 42054da8-aac2-4360-9041-c1cabda59306
  name: "Zolder Mini Marleen"
  device_class: running
  state: >-
    {{ is_state('media_player.zolder_mini_marleen', 'playing') }}
  delay_on: "00:00:05"
  delay_off: "00:00:05"
  attributes:
    volume: 0.25
