id: shelly_knop_slaapkamer
alias: "Eerste Verdieping | Slaapkamer - Acties met Shelly"
mode: parallel
max_exceeded: silent
trigger:
  - platform: event
    event_type: esphome.button_pressed
    event_data:
      device: Slaapkamer
action:
  - alias: "Lamp beschikbaar?"
    choose:
      - conditions: 
          - alias: "Lamp niet beschikbaar"
            condition: state
            entity_id: light.slaapkamer
            state: "unavailable"  
        sequence:
          - service: switch.toggle
            data:
              entity_id: switch.shelly_slaapkamer
    default:
      - alias: "Welk kliktype"
        choose:
          - conditions: 
              - alias: "Korte klik?"
                condition: template
                value_template: "{{ trigger.event.data.click_type == 'short' }}"
            sequence:
              - alias: "Lamp schakelen"
                service: light.toggle
                target:
                  entity_id: light.slaapkamer_template
          - conditions: 
              - alias: "Dubbelklik?"
                condition: template
                value_template: "{{ trigger.event.data.click_type == 'double' }}"
            sequence:
              - alias: "Licht aan op 100%"
                service: light.turn_on
                target:
                  entity_id: light.slaapkamer
                data:
                  brightness: 255
                  color_temp: "{{ state_attr('light.slaapkamer', 'min_mireds') }}"
          - conditions: 
              - alias: "Lange klik"
                condition: template
                value_template: "{{ trigger.event.data.click_type == 'long' }}"
            sequence:
              - alias: "Input boolean aanzetten"
                service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.dimmed_slaapkamer
              - alias: "Korte pauze"
                delay: 0.25
              - alias: "Lamp gedimd aan"
                service: light.turn_on
                target: 
                  entity_id: light.slaapkamer_template
                data:
                  brightness_pct: 5
                  color_temp: 360

