sensor:
  unique_id: f3d48dc4-3034-4bf9-85f9-3379c363a127
  name: Lichaamsvet Marleen
  state: "{{ state_attr('bodymiscale.marleen', 'body_fat') }}"
  state_class: measurement
  unit_of_measurement: '%'
  icon: mdi:hamburger