sensor:
  unique_id: 46497ab6-5b10-46d9-8a4f-f81161f10569
  name: Lichaamsvet Martijn
  state: "{{ state_attr('bodymiscale.martijn', 'body_fat') }}"
  state_class: measurement
  unit_of_measurement: '%'
  icon: mdi:hamburger