binary_sensor:
  unique_id: binary_temp_bedroom
  name: "Temperature Bedroom"
  device_class: window
  state: >-
    {{ 
      states('sensor.slaapkamer_temp') | float(0.0) > states('sensor.br_temperature') | float(0.0) 
      and states('sensor.slaapkamer_temp') | float(0.0) > 21
    }}
  delay_on: "00:05:00"
  delay_off: "00:05:00"
