input_select:
  region:
    name: Regio Schoolvakanties
    options:
      - Noord
      - Midden
      - Zuid
    icon: mdi:map-marker

sensor:
  - platform: rest
    name: Schoolvakanties vorig jaar
    resource_template: >
      {%- set y = now().year %}
      {%- set schoolyear = [y - 2, y - 1] | join('-') if now().month < 8 else [y - 1, y] | join('-') %}
      https://opendata.rijksoverheid.nl/v1/sources/rijksoverheid/infotypes/schoolholidays/schoolyear/{{ schoolyear }}?output=json
    value_template: "{{ value_json.type }}"
    json_attributes_path: "$.content[0]"
    json_attributes:
      - vacations
  - platform: rest
    name: Schoolvakanties huidig jaar
    resource_template: >
      {%- set y = now().year %}
      {%- set schoolyear = [y - 1, y] | join('-') if now().month < 8 else [y, y + 1] | join('-') %}
      https://opendata.rijksoverheid.nl/v1/sources/rijksoverheid/infotypes/schoolholidays/schoolyear/{{ schoolyear }}?output=json
    value_template: "{{ value_json.type }}"
    json_attributes_path: "$.content[0]"
    json_attributes:
      - vacations

template:
  - binary_sensor:
      unique_id: e038f350-3d72-4bef-a658-739077b0d419
      name: Schoolvakanties
      state: >
        {%- set list = state_attr('binary_sensor.schoolvakanties', 'vakanties') %}
        {%- set c = list | selectattr('start', '<=', now().date() | string) | selectattr('end', '>=', now().date() | string) | map(attribute='name') | join %}
        {{ iif(c) }}
      attributes:
        regio: "{{ states('input_select.region') }}"
        nu: >
          {%- set list = state_attr('binary_sensor.schoolvakanties', 'vakanties') %}
          {%- set c = list | selectattr('start', '<=', now().date() | string) | selectattr('end', '>=', now().date() | string) | map(attribute='name') | join %}
          {{ iif(c, c, 'Geen vakantie') }}
        vakanties: >
          {%- set vs = state_attr('sensor.schoolvakanties_vorig_jaar', 'vacations') %}
          {%- set r = state_attr('input_select.region', 'options').index(states('input_select.region')) %}
          {%- set n = vs[-1].type.strip() %}
          {%- set s = as_datetime(vs[-1].regions[r].startdate).date() | string %}
          {%- set e =  as_datetime(vs[-1].regions[r].enddate).date() | string %}
          {%- set o = dict(name=n, start=s, end=e) %}
          {%- set vs = state_attr('sensor.schoolvakanties_huidig_jaar', 'vacations') %}
          {%- set ns = namespace(v = []) %}
          {%- for v in vs %}
            {%- set n = v.type.strip() %}
            {%- set r = 0 if v.regions | count == 1 else r %}
            {%- set s = as_datetime(v.regions[r].startdate).date() | string %}
            {%- set e =  as_datetime(v.regions[r].enddate).date() | string %}
            {%- set ns.v = ns.v + [ dict(name=n, start=s, end=e) ] %}
          {%- endfor %}
          {{ [o] + ns.v }}
