id: 2068227c-13b2-4bc3-bc1b-50afe8da2deb
alias: "00 ⏱ Marleen is almost home"
mode: single
max_exceeded: silent
trigger:
  - platform: numeric_state
    entity_id: proximity.marleen
    below: 4000
condition:
  - alias: "Richting huis?"
    condition: state
    entity_id: proximity.marleen
    attribute: "dir_of_travel"
    state: "towards"
  - alias: "Marleen niet thuis?"
    condition: state
    entity_id: person.marleen
    state: "not_home"
  - alias: "Martijn wel thuis?"
    condition: state
    entity_id: person.martijn
    state: "home"
action:
  - alias: "Message to phone Martijn"
    service: notify.mobile_app_pixel_5
    data:
      title: "Hoera!"
      message: "Marleen is bijna thuis"
      data:
        channel: ETA
        ttl: 0
        priority: high
        notification_icon: mdi:party-popper
  - variables:
      target: >
        {% 
          if is_state('media_player.zolder_mini_martijn', 'playing')
          or is_state('sensor.location_phone_martijn', 'Zolder') 
        %}
          [ 'media_player.keuken_hub', 'media_player.zolder_mini_martijn' ]
        {% else %}
          [ 'media_player.keuken_hub' ]
        {% endif %}
  - alias: "Send TTS using Google Home Resume script"
    service: script.turn_on
    target:
      entity_id: script.google_home_resume
    data:
      variables:
        action:
          - alias: "Send TTS message"
            service: tts.google_cloud_say
            target:
              entity_id: "{{ target }}"
            data:
              message: "Hoera! Marleen is bijna thuis!"
  - alias: "Wait first target is idle or off (will prevent volume change of stream in case there is only one target)"
    wait_template: "{{ states(target[0]) in ['idle', 'off'] }}"
  - alias: "Apply TTS volume"
    service: media_player.volume_set
    target:
      entity_id: "{{ target }}"
    data:
      volume_level: 0.35
