id: c9932ea5-d3c1-4b8a-8849-e53179e5caf3
alias: "F1P 👦 Motion detection PepijnCam on and off"
mode: single
max_exceeded: silent
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: time
    at:
      - "07:30"
      - "12:30"
      - "16:30"
      - "19:30"
condition:
  - alias: "Someone home?"
    condition: state
    entity_id: group.m_en_m
    state: "home"
action:
  - alias: "Time?"
    choose:
      - conditions:
          - condition: time
            before: " 07:29:59"
        sequence:
          - alias: "Motion detection Pepijncam on"
            service: switch.turn_on
            target:
              entity_id: switch.pepijncam_state
      - conditions:
          - condition: time
            before: " 12:29:59"
        sequence:
          - alias: "Motion detection Pepijncam off"
            service: switch.turn_off
            target:
              entity_id: switch.pepijncam_state
      - conditions:
          - condition: time
            before: " 16:29:59"
          - alias: "No daycare or grandma?"
            condition: time
            weekday:
              - "wed"
              - "fri"
              - "sat"
              - "sun"
        sequence:
          - alias: "Motion detection Pepijncam on"
            service: switch.turn_on
            target:
              entity_id: switch.pepijncam_state
      - conditions:
          - condition: time
            before: "19:29:59"
          - alias: "No daycare or grandma?"
            condition: time
            weekday:
              - "wed"
              - "fri"
              - "sat"
              - "sun"
        sequence:
          - alias: "Motion detection Pepijncam off"
            service: switch.turn_off
            target:
              entity_id: switch.pepijncam_state
      - conditions:
          - condition: time
            after: "19:30:00"
        sequence:
          - alias: "Motion detection Pepijncam on"
            service: switch.turn_on
            target:
              entity_id: switch.pepijncam_state
