id: f343ab16-005f-4a46-bea0-450b060c07a4
alias: "F1F ⏺ Enable or disable recording of cameras Pepijn"
mode: single
max_exceeded: silent
trigger:
  - platform: state
    entity_id:
      - binary_sensor.pepijn_person_motion
    from: "unavailable"
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.cleaning_time
  - platform: time
    at:
      - "19:00"
      - "07:30"
  - platform: state
    entity_id: sensor.house_mode
    from:
variables:
  switches:
    - switch.pepijn_recordings
    - switch.pepijn_snapshots
    - switch.pepijn_detect
action:
  - alias: "Which action"
    choose:
      - conditions:
          - alias: "Cleaning time"
            condition: state
            entity_id: binary_sensor.cleaning_time
            state: "on"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: "{{ switches }}"
      - conditions:
          - condition: or
            conditions:
              - alias: "Bedtime"
                condition: time
                after: " 19:00:00"
              - condition: not
                conditions:
                  - alias: "Nobody home"
                    condition: state
                    entity_id: sensor.house_mode
                    state: "Thuis"
        sequence:
          - service: switch.turn_on
            target: "{{ switches }}"
    default:
      - service: switch.turn_on
        target:
          entity_id: "{{ switches | reject('search', 'recordings') | list }}"
      - service: switch.turn_off
        target:
          entity_id: "{{ switches | select('search', 'recordings') | list }}"
