id: c9932ea5-d3c1-4b8a-8849-e53179e5caf3
alias: "F1P 👦 Motion detection PepijnCam on and off"
mode: single
max_exceeded: silent
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: time
    at:
      - "07:00"
      - "19:00"
condition:
  - alias: "Someone home?"
    condition: state
    entity_id: group.m_en_m
    state: "home"
action:
  - alias: "Time?"
    choose:
      - conditions:
          - condition: time
            after: "19:00:00"
            before: "19:00:00"
        sequence:
          - alias: "Motion detection Pepijncam on"
            service: switch.turn_off
            target:
              entity_id: switch.pepijn_recordings
      - conditions:
          - condition: time
            after: "19:00:00"
            before: "19:00:00"
        sequence:
          - alias: "Motion detection Pepijncam on"
            service: switch.turn_on
            target:
              entity_id: switch.pepijn_recordings_recordings
