id: pepijn_reset_dim_boolean
alias: "Eerste Verdieping | Pepijn - Boolean met dim status weer uit zetten"
mode: single
max_exceeded: silent
trigger:
  - platform: time
    at:
      - input_datetime.pepijn_transition_on
      - input_datetime.pepijn_transition_off
      - input_datetime.pepijn_dim_on
      - input_datetime.pepijn_dim_off
condition:
  - alias: "Input boolean aan?"
    condition: state
    entity_id: input_boolean.dimmed_pepijn
    state: "on"
action:
  - alias: "Input boolean uit"
    service: input_boolean.turn_off
    target:
      entity_id: input_boolean.dimmed_pepijn

