alias: "ZZ 🧪 Automation for quick tests"
trigger:
  - platform: numeric_state
    entity_id: input_number.test
    above: 10
  - platform: numeric_state
    entity_id: input_number.test
    above: 20
  - platform: numeric_state
    entity_id: input_number.test
    above: 30
action: []
