trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: media_player
      service: play_media
      service_data:
        media_content_type: music
        entity_id: ["media_player.vlc_telnet"]
sensor:
  - name: TTS Dummy
    unique_id: 059c2595-7308-4259-a320-2ee37eb2f5b0
    state: "{{ trigger.event.data.service_data.media_content_id }}"
    icon: mdi:text-box
