id: deur_trapkast
alias: "Beneden | Trapkast - Lamp aan en uit met deur"
mode: restart
max_exceeded: silent
trigger:
  - platform: state
    entity_id: binary_sensor.deur_trapkast
action:
  - alias: "Open of dicht?"
    choose:
    - conditions:
        - alias: "Trapkast open?"
          condition: state
          entity_id: binary_sensor.deur_trapkast
          state: "on"
      sequence:
        - alias: "Licht aan"
          service: light.turn_on
          target:
            entity_id: light.trapkast
          data:
            brightness: 255
            color_temp: 154
        - delay: 300
        - alias: "Licht uit"
          service: light.turn_off
          target:
            entity_id: light.trapkast
    - conditions:
        - alias: "Trapkast dicht?"
          condition: state
          entity_id: binary_sensor.deur_trapkast
          state: "off"
      sequence:
        - alias: "Licht uit"
          service: light.turn_off
          target:
            entity_id: light.trapkast
