binary_sensor:
  - platform: ping
    host: 192.168.2.2
    name: "Computer Zolder"
    count: 2
    scan_interval: 5
  - platform: ping
    host: 192.168.2.100
    name: "Fritz Box"
    count: 2
    scan_interval: 5
  - platform: ping
    host: 192.168.2.164
    name: "Fritz Repeater Woonkamer"
    count: 2
    scan_interval: 5
  - platform: ping
    host: 192.168.2.165
    name: "Fritz Repeater Slaapkamer"
    count: 2
    scan_interval: 5
  - platform: ping
    host: 192.168.2.167
    name: "Fritz Repeater Zolder"
    count: 2
    scan_interval: 5
  - platform: ping
    host: 192.168.2.89
    name: "iMac Marleen"
    count: 2
    scan_interval: 5
  - platform: ping
    host: 192.168.2.90
    name: "Camera Pepijn"
    count: 2
    scan_interval: 5
  - platform: ping
    host: 192.168.2.91
    name: "Camera Floris"
    count: 2
    scan_interval: 5
  - platform: ping
    host: 192.168.2.87
    name: "Laptop Werk Martijn Wifi"
    count: 2
    scan_interval: 5
  - platform: ping
    host: 192.168.2.88
    name: "Laptop Werk Martijn LAN"
    count: 2
    scan_interval: 5
  - platform: workday
    country: NL
    workdays: [mon, tue, thu, fri]
    excludes: [wed, sat, sun, holiday]
