id: dimmer_lamp_gedimd_aan
alias: "Beneden | Lampen - Shelly dimmers gedimd aan"
mode: parallel
max_exceeded: silent
trigger:
  - platform: state
    entity_id:
      - light.keuken
      - light.wc
      - light.woonkamer_plafond
    from: "off"
    to: "on"
variables:
  light: "{{ trigger.to_state.entity_id }}"
  name: "{{ trigger.to_state.entity_id | replace('light.', '') }}"
  bright: >
    {% if name == 'wc' %}
      80
    {% elif name == 'keuken' %}
      30
    {% else %}
      50
    {% endif %}
action:
  - alias: "Helderheid lamp aanpassen"
    service: light.turn_on
    target:
      entity_id: "{{ light }}"
    data:
      brightness: "{{ bright }}"
