id: f3e6111a-8c48-4eb8-9819-1f33b66fd50c
alias: "F1M 🛌 Screens down when it is sunny and warm"
trigger:
  - platform: time
    at: "12:30"
condition:
  - alias: "Warm"
    condition: template
    value_template: "{{ state_attr('weather.climacell_daily', 'forecast')[0].temperature | float(0.0) >= 23 }}"
  - condition: or
    conditions:
      - alias: "Sunny?"
        condition: template
        value_template: "{{ state_attr('weather.climacell_daily', 'forecast')[0].condition == 'sunny' }}"
      - alias: "Partly cloudy?"
        condition: template
        value_template: "{{ state_attr('weather.climacell_daily', 'forecast')[0].condition == 'partlycloudy' }}"
  - alias: "No rain upcoming?"
    condition: template
    value_template: "{{ state_attr('weather.climacell_hourly', 'forecast')[:4] | map(attribute='precipitation') | sum | float(0.0) == 0 }}"
action:
  - alias: "Sreens down"
    service: cover.open_cover
    target:
      entity_id:
        - cover.slaapkamer_groep
