id: 43077f87-25be-4516-b241-0db9d1e4ff98
alias: "F1 🏠 Start vacuum cleaner on Monday"
trigger:
  - id: vacuum
    platform: time
    at:
      - "08:00:00"
      - "09:00:00"
condition:
  - alias: "Monday?"
    condition: time
    weekday:
      - "mon"
action:
  - variables:
      external_url: !secret ha_url
  - alias: "Action?"
    choose:
      - conditions:
          - alias: "Na 9u?"
            condition: time
            after: "09:00:00"
        sequence:
          - service: vacuum.start
            target:
              entity_id: vacuum.rockrobo_vacuum_v1
    default:
      - alias: "Notification to phone Marleen"
        service: notify.mobile_app_marleen_app
        data:
          message: "Is alles van de grond?"
          title: "De stofzuiger begint om 09:00"
      - alias: "Notification to phone Martijn"
        service: notify.join_pixel5
        data:
          message: "Is alles van de grond?"
          title: "De stofzuiger begint om 09:00"
          data:
            icon: "{{ external_url }}/local/pictures/broom.png"
            smallicon: "{{ external_url }}/local/pictures/broom.png"
