id: start_stofzuiger
alias: "Eerste Verdieping - Stofzuigen op maandag"
trigger:
  - id: vacuum
    platform: time
    at:
      - "08:00:00"
      - "09:00:00"
condition:
  - alias: "Is het maandag?"
    condition: time
    weekday:
      - "mon"
action:
  - variables:
      external_url: !secret ha_url
  - alias: "Welke actie?"
    choose:
      - conditions:
          - alias: "Na 9u?"
            condition: time
            after: "09:00:00"
        sequence:
          - service: vacuum.start
            target:
              entity_id: vacuum.rockrobo_vacuum_v1
    default:
      - alias: "Bericht naar telefoon Marleen"
        service: notify.mobile_app_marleen_app
        data:
          message: "Is alles van de grond?"
          title: "De stofzuiger begint om 09:00"
      - alias: "Bericht naar telefoon Martijn"
        service: notify.join_pixel5
        data:
          message: "Is alles van de grond?"
          title: "De stofzuiger begint om 09:00"
          data:
            icon: "{{ external_url }}/local/pictures/broom.png"
            smallicon: "{{ external_url }}/local/pictures/broom.png"
