id: return_stofzuiger
alias: "F1 🏠 Vacuum back to dock in case it's doing nothing"
trigger:
  - id: paused_return
    platform: state
    entity_id: vacuum.rockrobo_vacuum_v1
    from: "cleaning"
    to:
      - "paused"
      - "idle"
    for: "00:15:00"
action:
  - variables:
      external_url: !secret ha_url
  - alias: "Notification to phone Marleen"
    service: notify.mobile_app_marleen_app
    data:
      message: "De stofzuiger staat al een kwartier te nietsnutten, en gaat over 10 minuten terug naar z'n dock"
      title: "Stofzuiger terug naar dock"
  - alias: "Notification to phone Martijn"
    service: notify.join_pixel5
    data:
      message: "De stofzuiger staat al een kwartier te nietsnutten, en gaat over 10 minuten terug naar z'n dock"
      title: "Stofzuiger terug naar dock"
      data:
        icon: "{{ external_url }}/local/pictures/broom.png"
        smallicon: "{{ external_url }}/local/pictures/broom.png"
  - delay: 10
  - alias: "Still doing nothing?"
    condition: state
    entity_id: vacuum.rockrobo_vacuum_v1
    state:
      - idle
      - paused
  - alias: "Return to dock"
    service: vacuum.return_to_base
    target:
      entity_id: vacuum.rockrobo_vacuum_v1
