id: 501645e8-f419-4349-9f0b-57a2f915b345
alias: "F1 🏠 Notifications vacuum cleaner"
mode: single
max_exceeded: silent
trigger:
  - platform: state
    entity_id: vacuum.rockrobo_vacuum_v1
    from: returning
    to: docked
  - platform: state
    entity_id: vacuum.rockrobo_vacuum_v1
    to: error
action:
  - alias: "Stofzuiger in dock?"
    choose:
      - conditions:
          - alias: "Docked?"
            condition: state
            entity_id: vacuum.rockrobo_vacuum_v1
            state: "docked"
        sequence:
          - alias: "Notification to phones"
            service: notify.all_phones
            data:
              message: "De stofzuiger is klaar en staat weer op z'n plek"
              title: "Stofzuiger is klaar"
              data:
                ttl: 0
                priority: high
      - conditions:
          - alias: "Docked?"
            condition: state
            entity_id: vacuum.rockrobo_vacuum_v1
            state: "error"
        sequence:
          - alias: "Notification to phones"
            service: notify.all_phones
            data:
              title: "Probleem met stofzuiger"
              message: "Er is iets mis met de stofzuiger. De melding is: {{ state_attr('vacuum.rockrobo_vacuum_v1', 'error') }}"
              data:
                ttl: 0
                priority: high
