id: zon_screens_achter
alias: "F1 🏠 Screens down when it is sunny"
trigger:
  - platform: time
    at: "19:30"
  - platform: state
    entity_id: binary_sensor.regen_tot_ochtend
    from: "on"
    to: "off"
  - platform: state
    entity_id: binary_sensor.regen_tot_middag
    from: "on"
    to: "off"
variables:
  day: "{{ 0 if now().hour < 13 else 1 }}"
condition:
  - alias: "Warm"
    condition: template
    value_template: >
      {{ 
        state_attr('weather.climacell_daily', 'forecast')[day | int].temperature | float(20.0) 
        >= 21
      }}
  - alias: "Sunny or partly cloudy?"
    condition: template
    value_template: >
      {{ 
        state_attr('weather.climacell_daily', 'forecast')[day | int].condition 
        in ['sunny', 'partly_cloudy'] 
      }}
  - alias: "Rain upcoming?"
    condition: template
    value_template: >
      {{ 
        is_state('binary_sensor.regen_tot_middag', 'off') if now().hour < 13 
        else is_state('binary_sensor.regen_tot_ochtend', 'off') 
      }}
  - alias: "Not after the sun is not at this side of the house"
    condition: time
    after: "19:29:59"
    before: "14:00:00"
action:
  - service: cover.close_cover
    target:
      entity_id:
        - cover.pepijn
        - cover.floris
