<<: !include tmpl_wifi_no_sensors.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: True
    name: "${device_name} ${device_type} button"
    internal: true
    on_press:
      - light.toggle: light_id

output:
  - platform: esp8266_pwm
    id: led
    pin:
      number: GPIO13
      inverted: true
  - platform: gpio
    pin: GPIO14
    id: main_light_relay

light:
  - platform: monochromatic
    id: status_led
    name: ${device_name} ${device_type} Led
    output: led
    internal: true
  - platform: binary
    name: ${device_name}
    output: main_light_relay
    id: light_id
    on_turn_on:
      - light.turn_on: status_led
    on_turn_off:
      - light.turn_off: status_led

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "${device_name} ${device_type} Amperage"
      unit_of_measurement: A
    voltage:
      name: "${device_name} ${device_type} Voltage"
      unit_of_measurement: V
    power:
      name: "${device_name} ${device_type} Power"
      unit_of_measurement: W
      id: "wattage"
    change_mode_every: 8
    update_interval: 10s
  - platform: total_daily_energy
    name: "${device_name} ${device_type} Total Daily Energy"
    power_id: "wattage"
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: wifi_signal
    name: ${device_name} ${device_type} Wifi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: ${device_name} ${device_type} Uptime

button:
  - platform: restart
    name: "${device_name} ${device_type} Restart"

text_sensor:
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${device_name} ${device_type} IP
