<<: !include tmpl_wifi_sensors.yaml

binary_sensor:
  - platform: status
    name: ${device_name} Status
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    name: ${device_name} Button
    internal: true
    on_press:
      - light.toggle: light_id

output:
  - platform: esp8266_pwm
    id: led
    pin:
      number: GPIO4
      inverted: true
  - platform: gpio
    pin: GPIO12
    id: main_light_relay

light:
  - platform: monochromatic
    id: status_led
    name: ${device_name} Light
    output: led
    internal: true
  - platform: binary
    name: ${device_name}
    output: main_light_relay
    id: light_id
    on_turn_on:
      - light.turn_on: status_led
    on_turn_off:
      - light.turn_off: status_led

button:
  - platform: restart
    name: "${device_name} ${device_type} Restart"
