<<: !include tmpl_wifi_no_sensors.yaml

# ble tracker
esp32_ble_tracker:

#binary_sensor:
#  # Presence based on MAC address
#  - platform: ble_presence
#    mac_address: 14:8F:21:FD:CE:BC
#    name: "Garmin Horloge Martijn"
#  # Presence based on iBeacon UUID
#  - platform: ble_presence
#    ibeacon_uuid: '54d20ec9-8b18-4345-baf1-c87c67ed3cc9'
#    name: "Telefoon Martijn"

sensor:
  #  - platform: ble_rssi
  #    mac_address: 14:8F:21:FD:CE:BC
  #    name: "Garmin Horloge Martijn RSSI"
  #  - platform: ble_rssi
  #    service_uuid: '54d20ec9-8b18-4345-baf1-c87c67ed3cc9'
  #    name: "Telefoon Martijn RSSI"
  - platform: wifi_signal
    name: ${device_name} ${device_type} Wifi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: ${device_name} ${device_type} Uptime
  - platform: xiaomi_miscale
    mac_address: "50:FB:19:17:34:96"
    weight:
      name: "Xiaomi Mi Scale Weight"
      id: weight_miscale
      on_value:
        then:
          - lambda: |-
              if (id(weight_miscale).state >= 69 && id(weight_miscale).state <= 77.49) {
                return id(weight_user2).publish_state(x);}
              else if (id(weight_miscale).state >= 77.50 && id(weight_miscale).state <= 83) {
                return id(weight_user1).publish_state(x);}
    impedance:
      name: "Xiaomi Mi Scale Impedance"
      id: impedance_xiaomi
      on_value:
        then:
          - lambda: |-
              if (id(weight_miscale).state >= 69 && id(weight_miscale).state <= 77.49) {
                return id(impedance_user2).publish_state(x);}
              else if (id(weight_miscale).state >= 77.50 && id(weight_miscale).state <= 83) {
                return id(impedance_user1).publish_state(x);}
  - platform: template
    name: Weight Martijn
    id: weight_user1
    unit_of_measurement: "kg"
    state_class: "measurement"
    icon: mdi:weight-kilogram
    accuracy_decimals: 2
  - platform: template
    name: Impedance Martijn
    id: impedance_user1
    unit_of_measurement: "ohm"
    icon: mdi:omega
    accuracy_decimals: 0
  - platform: template
    name: Weight Marleen
    id: weight_user2
    unit_of_measurement: "kg"
    icon: mdi:weight-kilogram
    state_class: "measurement"
    accuracy_decimals: 2
  - platform: template
    name: Impedance Marleen
    id: impedance_user2
    unit_of_measurement: "ohm"
    icon: mdi:omega
    accuracy_decimals: 0

text_sensor:
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${device_name} ${device_type} IP
