id: afzuigkap_aan_ochtend
alias: "Beneden | Keuken - Afzuigkap weer aan in ochtend"
mode: single
max_exceeded: silent
trigger:
  - platform: state
    entity_id: light.groep_beneden
    to: "on"
condition:
  - alias: "Afzuigkap uit?"
    condition: state
    entity_id: switch.afzuigkap
    state: "off"
action:
  - alias: "Afzuigkap plug aan"
    service: switch.turn_on
    target:
      entity_id: switch.afzuigkap