id: 341786d9-1a4e-4328-be86-1e3d68d5744c
alias: "F0K 🍳 Dishwasher timer and notification"
mode: single
max_exceeded: silent
trigger:
  - platform: state
    entity_id: binary_sensor.dishwasher_active
    from:
      - "on"
      - "off"
action:
  - variables:
      external_url: !secret ha_url
  - alias: "Select action"
    choose:
      - conditions:
          - alias: "Vaatwasser on"
            condition: state
            entity_id: binary_sensor.dishwasher_active
            state: "on"
          - alias: "Timer not set yet"
            condition: time
            after: input_datetime.dishwasher_program
        sequence:
          - alias: "Set timer (input_datetime)"
            service: input_datetime.set_datetime
            target:
              entity_id: input_datetime.dishwasher_program
            data:
              timestamp: "{{ (now() | as_timestamp + (3.5 * 3600)) | int }}"
      - conditions:
          - alias: "Vaatwasser off"
            condition: state
            entity_id: binary_sensor.dishwasher_active
            state: "off"
        sequence:
          - alias: "Timer off"
            service: input_datetime.set_datetime
            target:
              entity_id: input_datetime.dishwasher_program
            data:
              timestamp: "{{ (now() | as_timestamp) | int }}"
          - alias: "Notification"
            service: notify.join_pixel5
            data:
              title: "De vaatwasser is klaar"
              message: "Doe hem snel open zodat hij kan uitwasemen"
              data:
                icon: "{{ external_url }}/local/pictures/dish.png"
                smallicon: "{{ external_url }}/local/pictures/dish.png"
