id: 341786d9-1a4e-4328-be86-1e3d68d5744c
alias: "F0K 🍳 Dishwasher timer and notification"
mode: single
max_exceeded: silent
trigger:
  - platform: state
    entity_id: binary_sensor.dishwasher_active
    from:
      - "on"
      - "off"
action:
  - variables:
      external_url: !secret ha_url
  - delay: 10
  - alias: "Select action"
    choose:
      - conditions:
          - alias: "Vaatwasser on"
            condition: state
            entity_id: binary_sensor.dishwasher_active
            state: "on"
          - alias: "Timer not yet active"
            condition: state
            entity_id: timer.vaatwasser_timer
            state: "idle"
        sequence:
          - alias: "Timer on"
            service: timer.start
            target:
              entity_id: timer.vaatwasser_timer
      - conditions:
          - alias: "Vaatwasser off"
            condition: state
            entity_id: binary_sensor.dishwasher_active
            state: "off"
        sequence:
          - alias: "Timer off"
            service: timer.finish
            target:
              entity_id: timer.vaatwasser_timer
          - alias: "Notification"
            service: notify.join_pixel5
            data:
              title: "De vaatwasser is klaar"
              message: "Doe hem snel open zodat hij kan uitwasemen"
              data:
                icon: "{{ external_url }}/local/pictures/dish.png"
                smallicon: "{{ external_url }}/local/pictures/dish.png"
