id: buitenlampen
alias: "Buiten - Buitenlampen aan bij zonsondergang en uit om middernacht of zonsopkomst"
mode: single
max_exceeded: silent
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: sun.sun
    to:
      - "above_horizon"
      - "below_horizon"
  - platform: time
    at: 
      - "00:00"
      - "06:30"
action:
  - alias: "Middernacht zonsopkomst, zonsondergang of vroeg in de ochtend?"
    choose:
    - conditions:
        - alias: "Middernacht?"
          condition: time
          before: " 00:15:00"
      sequence:
        - alias: "Lampen tuin uit"
          service: light.turn_off
          target:
            entity_id: 
              - light.tuinlampjes
              - light.veranda
    - conditions:
        - alias: "Zon op?"
          condition: state
          entity_id: sun.sun
          state: "above_horizon"
      sequence:
        - alias: "Alle buitenlampen uit"
          service: light.turn_off
          target:
            entity_id: 
              - light.groep_buiten
    - conditions:
        - alias: "Zon onder?"
          condition: state
          entity_id: sun.sun
          state: "below_horizon"
      sequence:
        - alias: "Lamp voordeur en tuinlampjes aan"
          service: light.turn_on    
          target:
            entity_id: 
              - light.tuinlampjes
              - light.voordeur
        - alias: "Lichten veranda gedimd aan"
          service: light.turn_on
          target:
            entity_id: light.veranda
          data:
            brightness: 10 
        - alias: "Pauze van 10 seconden"
          delay: 10
        - alias: "Nog een keer veranda aan voor de zekerheid"
          service: light.turn_on
          target:  
            entity_id: light.veranda
          data:
            brightness: 10 