id: 3f3a1b56-9c34-47e1-b50f-2b96838b7133
alias: "F0Z 🌳 Notificaties for trash containers"
mode: single
max_exceeded: silent
trigger:
  - platform: time
    id: morning
    at:
      - "07:00:00"
  - platform: time
    id: evening
    at:
      - "20:00:00"
action:
  - variables:
      external_url: !secret ha_url
  - alias: "Evening before, of day of trash day?"
    choose:
      - conditions:
          - condition: not
            conditions:
              - alias: "Trash day tomorrow?"
                condition: state
                entity_id: sensor.mijnafvalwijzer_morgen
                state: "Geen"
          - alias: "Evening?"
            condition: trigger
            id: evening
        sequence:
          - alias: "Notification phone Marleen"
            service: notify.mobile_app_marleen_app
            data:
              title: "Denk aan de container"
              message: "Morgen moet de {{ 'Rest- en GFT-bak' if is_state('sensor.mijnafvalwijzer_morgen', 'duobak') else 'Papier- en PMD-bak' }} buiten"
          - alias: "Notification phone Martijn"
            service: notify.join_pixel5
            data:
              message: "Morgen moet de {{ 'Rest- en GFT-bak' if is_state('sensor.mijnafvalwijzer_morgen', 'duobak') else 'Papier- en PMD-bak' }} buiten"
              title: "Denk aan de container"
              data:
                icon: "{{ external_url }}/local/pictures/waste.png"
                smallicon: "{{ external_url }}/local/pictures/waste.png"
      - conditions:
          - condition: not
            conditions:
              - alias: "Trash day today?"
                condition: state
                entity_id: sensor.mijnafvalwijzer_vandaag
                state: "Geen"
          - alias: "Morning?"
            condition: trigger
            id: morning
        sequence:
          - alias: "Notification phone Marleen"
            service: notify.mobile_app_marleen_app
            data:
              title: "Denk aan de container"
              message: "Vandaag moet de {{ 'Rest- en GFT-bak' if is_state('sensor.mijnafvalwijzer_vandaag', 'duobak') else 'Papier- en PMD-bak' }} buiten"
          - alias: "Notification phone Martijn"
            service: notify.join_pixel5
            data:
              message: "Vandaag moet de {{ 'Rest- en GFT-bak' if is_state('sensor.mijnafvalwijzer_vandaag', 'duobak') else 'Papier- en PMD-bak' }} buiten"
              title: "Denk aan de container"
              data:
                icon: "{{ external_url }}/local/pictures/waste.png"
                smallicon: "{{ external_url }}/local/pictures/waste.png"
