id: 3f3a1b56-9c34-47e1-b50f-2b96838b7133
alias: "F0Z 🌳 Notificaties for trash containers"
mode: single
max_exceeded: silent
trigger:
  - platform: time
    id: Morgen
    at:
      - "07:00:00"
  - platform: time
    id: Vandaag
    at:
      - "20:00:00"
variables:
  sensor: "sensor.mijnafvalwijzer_{{ trigger.id | lower }}"
  trash_descr:
    duobak: "Rest- en GFT-bak"
    papier-pmd: "Papier- en PMD-bak"
condition:
  - alias: "Notification needed?"
    condition: template
    value_template: "{{ states(sensor) != 'Geen' }}"
action:
  - variables:
      trash_type: "{{ trash_descr[states(sensor)] }}"
  - alias: "Notification phones"
    service: notify.all_phones
    data:
      title: "Denk aan de container"
      message: "{{ trigger.id }} moet de {{ trash_type }} buiten"
      data:
        channel: Trash
        ttl: 0
        priority: high
        notification_icon: mdi:trash-can-outline
