id: 3f3a1b56-9c34-47e1-b50f-2b96838b7133
alias: "F0Z 🌳 Notificaties for trash containers"
mode: single
max_exceeded: silent
trigger:
  - platform: time
    id: today
    at:
      - "07:00:00"
  - platform: time
    id: tomorrow
    at:
      - "20:00:00"
conditons:
  - alias: "Notification needed?"
    condition: template
    value_template: >
      {{ 
        (trigger.id == 'today' and not is_state('sensor.mijnafvalwijzer_vandaag', 'Geen'))
        or
        (trigger.id == 'tomorrow' and not is_state('sensor.mijnafvalwijzer_morgen', 'Geen'))
      }}
action:
  - variables:
      trash_type: >
        {% set type = 
          states('sensor.mijnafvalwijzer_vandaag') if trigger.id == 'today' 
          else states('sensor.mijnafvalwijzer_morgen') 
        %}
        {{
          'Rest- en GFT-bak' if type == 'duobak'
          else 'Papier- en PMD-bak'
        }}
      notification_moment: >
        {{ 'Vandaag' if trigger.id == 'today' else 'Morgen' }}
  - alias: "Notification phones"
    service: notify.all_phones
    data:
      title: "Denk aan de container"
      message: "{{ notification_moment }} moet de {{ trash_type }} buiten"
      data:
        channel: Trash
        ttl: 0
        priority: high
        notification_icon: mdi:trash-can-outline
