sensor:
  - name: Energy high tariff
    unique_id: 271b931a-9454-40f8-aa54-0af52b1077cb
    state: >
      {{
        [
          state_attr('sensor.energy_high_tariff', 'delivery'),
          state_attr('sensor.energy_high_tariff', 'tax'),
          state_attr('sensor.energy_high_tariff', 'storage')
        ] | map('float', 0) | sum
      }}
    icon: mdi:cash
    unit_of_measurement: "€/kWh"
    attributes:
      delivery: 0.09595
      tax: 0.11408
      storage: 0.03630
