sensor:
  - name: Energy low tariff
    unique_id: a89ba420-ee99-40df-8031-41986897b169
    state: >
      {{
        [
          state_attr('sensor.energy_low_tariff', 'delivery'),
          state_attr('sensor.energy_low_tariff', 'tax'),
          state_attr('sensor.energy_low_tariff', 'storage')
        ] | map('float', 0) | sum
      }}
    icon: mdi:cash
    unit_of_measurement: "€/kWh"
    attributes:
      delivery: 0.08978
      tax: 0.11408
      storage: 0.03630
