sensor:
  - name: Gas tariff
    unique_id: e8e5e0e0-652e-4cca-9cc4-20b491ec585b
    state: >
      {{
        [
          state_attr('sensor.gas_tariff', 'delivery'),
          state_attr('sensor.gas_tariff', 'tax'),
          state_attr('sensor.gas_tariff', 'storage')
        ] | map('float', 0) | sum
      }}
    icon: mdi:cash
    unit_of_measurement: "€/m³"
    attributes:
      delivery: 0.35396
      tax: 0.42176
      storage: 0.10297
