substitutions:
  device_name: Backup 01
  device_type: Plug
  # Higher value gives lower watt readout
  current_res: "0.00221"
  # Lower value gives lower voltage readout
  voltage_div: "800"
  ip: 192.168.2.34

esphome:
  name: backup01
  platform: ESP8266
  board: esp8285

<<: !include common/tmpl_neo_coolcam16_switch.yaml 
