substitutions:
  device_name: Eettafel
  device_type: Shelly1
  device_lower: eettafel
  light_device: light.eettafel
  ip: 192.168.2.14

esphome:
  name: ${device_lower}
  platform: ESP8266
  board: esp01_1m

# Shelly 1 detached switch config with multiclick options and connection fail fallback
<<: !include common/tmpl_shelly1_detached_multi.yaml
