substitutions:
  device_name: Floris
  device_type: Shelly1
  device_lower: floris
  ip: 192.168.2.16

esphome:
  name: ${device_lower}
  platform: ESP8266
  board: esp01_1m

# Shelly 1 detached switch config with multiclick options and connection fail fallback
<<: !include common/tmpl_shelly1_detached_multi.yaml