substitutions:
  device_name: Speelhoek
  device_type: Light
  ip: 192.168.2.38

esphome:
  name: speelhoek
  platform: ESP8266
  board: esp01_1m

# Config LSC Filament bulb
<<: !include common/tmpl_lsc_filament.yaml
#<<: !include common/tmpl_wifi_minimal.yaml